apiVersion: v1
kind: Service
metadata:
  name: arthproxy-headless
spec:
  ports:
    - name: tcp
      port: 50052
      protocol: TCP
      targetPort: 50052
  selector:
    app/name: arthproxy
  type: NodePort
