package signal

import (
	"arthas/etcd"
	"github.com/go-kit/log/level"
	"github.com/google/uuid"
	"go.etcd.io/etcd/api/v3/mvccpb"
	"google.golang.org/protobuf/proto"
	"math/rand"
	"strconv"
	"strings"
	"time"
)

type userDeviceCifg struct {
	OsVersion     *string `protobuf:"bytes,5,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	Device        *string `protobuf:"bytes,7,opt,name=device" json:"device,omitempty"`
	OsBuildNumber *string `protobuf:"bytes,8,opt,name=os_build_number,json=osBuildNumber" json:"os_build_number,omitempty"`
	PhoneId       *string `protobuf:"bytes,9,opt,name=phone_id,json=phoneId" json:"phone_id,omitempty"`
}

type AppVersion struct {
	Primary    *uint32 `protobuf:"varint,1,opt,name=primary" json:"primary,omitempty"`
	Secondary  *uint32 `protobuf:"varint,2,opt,name=secondary" json:"secondary,omitempty"`
	Tertiary   *uint32 `protobuf:"varint,3,opt,name=tertiary" json:"tertiary,omitempty"`
	Quaternary *uint32 `protobuf:"varint,4,opt,name=quaternary" json:"quaternary,omitempty"`
	Quinary    *uint32 `protobuf:"varint,5,opt,name=quinary" json:"quinary,omitempty"`
}

func (m *Manager) GetAppVersionFromEtcd() AppVersion {
	if m.appVersion.IsEmpty() {
		getReq := etcd.GetReq{
			Key:     "whatsapp/appVersion",
			Options: nil,
			ResChan: make(chan etcd.GetRes),
		}
		m.getChan <- getReq
		res := <-getReq.ResChan
		if res.Result.Kvs != nil {
			return m.VersionAnalyzeToUserAgent(res.Result.Kvs[0].Value)
		} else {
			// 如果etcd没有版本号 则添加进去
			put := etcd.PutReq{
				Key:     "whatsapp/appVersion",
				Value:   "2.23.11.76",
				Options: nil,
				ResChan: make(chan etcd.PutRes),
			}
			m.putChan <- put
			m.appVersion = AppVersion{
				Primary:    proto.Uint32(2),
				Secondary:  proto.Uint32(23),
				Tertiary:   proto.Uint32(11),
				Quaternary: proto.Uint32(76),
			}
		}
	}
	return m.appVersion

}

func (m *Manager) MonitorAppVersion() {
	for {
		watchKVChan := m.whatChan
		reqModel := etcd.WatchReq{
			Key:     "whatsapp/appVersion",
			ResChan: make(chan etcd.WatchRes),
		}
		watchKVChan <- reqModel
		for res := range reqModel.ResChan {
			for _, ev := range res.Events {
				switch ev.Type {
				case mvccpb.PUT:
					v := ev.Kv.Value
					m.VersionAnalyzeToUserAgent(v)
					level.Info(m.logger).Log("etcd修改版本号：" + string(v))
				case mvccpb.DELETE:
					level.Error(m.logger).Log("whatsApp etcd版本被删除！")
					panic("whatsApp etcd版本被删除！")
				}
				//fmt.Printf("%s %q : %q\n", ev.Type, ev.Kv.Key, ev.Kv.Value)
			}
		}
	}
}

func (a AppVersion) IsEmpty() bool {
	return a.Primary == nil && a.Secondary == nil && a.Tertiary == nil && a.Quaternary == nil && a.Quinary == nil
}

func (m *Manager) VersionAnalyzeToUserAgent(version []byte) AppVersion {
	v := strings.Split(string(version), ".")
	primary, e1 := strconv.ParseUint(v[0], 10, 32)
	secondary, e2 := strconv.ParseUint(v[1], 10, 32)
	tertiary, e3 := strconv.ParseUint(v[2], 10, 32)
	quaternary, e4 := strconv.ParseUint(v[3], 10, 32)
	if e1 != nil || e2 != nil || e3 != nil || e4 != nil {
		panic("解析whatsapper版本报错")
	}
	m.appVersion = AppVersion{
		Primary:    proto.Uint32(uint32(primary)),
		Secondary:  proto.Uint32(uint32(secondary)),
		Tertiary:   proto.Uint32(uint32(tertiary)),
		Quaternary: proto.Uint32(uint32(quaternary)),
	}
	return m.appVersion
}

func GetRandomUserDeviceConfig() userDeviceCifg {
	globaleUserDeviceConfigs := []userDeviceCifg{
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("2E253")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("2E248")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20A371")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0.1"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20A371")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 14 pro max"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0.1"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20A371")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 14 pro"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0.1"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20A371")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 14 puls"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0.1"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20A371")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone14"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone SE 第 三代"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone SE 第三代"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone SE  第三代"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone SE 第三代"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone SE  第三代"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone SE 第三代"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone SE  第三代"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone SE  第三代"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone SE 第三代"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone SE 第三代"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone SE  第三代"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone SE 第三代"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone SE 第三代"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone SE 第 三代"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone SE 第三代"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone SE 第 三代"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone SE 第 三代"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone SE 第三代"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone SE  第三代"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19C57")},
		{OsVersion: proto.String("15.1.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19B81")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone 13"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19C57")},
		{OsVersion: proto.String("15.1.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19B81")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone 13 mini"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19C57")},
		{OsVersion: proto.String("15.1.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19B81")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone 13 pro max"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20B182")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19C57")},
		{OsVersion: proto.String("15.1.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19B81")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone 13 pro"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19C56")},
		{OsVersion: proto.String("15.1.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19B81")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("14.8"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("18H17")},
		{OsVersion: proto.String("14.6"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("18F72")},
		{OsVersion: proto.String("14.5.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("18E212")},
		{OsVersion: proto.String("14.5"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("18E199")},
		{OsVersion: proto.String("14.4.2"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("18D70")},
		{OsVersion: proto.String("14.4.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("18D61")},
		{OsVersion: proto.String("14.4"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("18D52")},
		{OsVersion: proto.String("14.3"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("18C66")},
		{OsVersion: proto.String("14.2.1"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("18B121")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphone 12 pro"), OsBuildNumber: proto.String("18B111")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19C56")},
		{OsVersion: proto.String("15.1.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19B81")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("14.8"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18H17")},
		{OsVersion: proto.String("14.6"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18F72")},
		{OsVersion: proto.String("14.5.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18E212")},
		{OsVersion: proto.String("14.5"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18E199")},
		{OsVersion: proto.String("14.4.2"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18D70")},
		{OsVersion: proto.String("14.4.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18D61")},
		{OsVersion: proto.String("14.4"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18D52")},
		{OsVersion: proto.String("14.3"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18C66")},
		{OsVersion: proto.String("14.2.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18B121")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18B111")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18B92")},
		{OsVersion: proto.String("14.1"), Device: proto.String("iphone 12 pro max"), OsBuildNumber: proto.String("18A8395")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19C56")},
		{OsVersion: proto.String("15.1.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19B81")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("14.8"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18H17")},
		{OsVersion: proto.String("14.6"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18F72")},
		{OsVersion: proto.String("14.5.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18E212")},
		{OsVersion: proto.String("14.5"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18E199")},
		{OsVersion: proto.String("14.4.2"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18D70")},
		{OsVersion: proto.String("14.4.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18D61")},
		{OsVersion: proto.String("14.4"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18D52")},
		{OsVersion: proto.String("14.3"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18C66")},
		{OsVersion: proto.String("14.2.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18B121")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18B111")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18B92")},
		{OsVersion: proto.String("14.1"), Device: proto.String("iphone 12 mini"), OsBuildNumber: proto.String("18A8395")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19C56")},
		{OsVersion: proto.String("15.1.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19B81")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("14.8"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18H17")},
		{OsVersion: proto.String("14.7.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18G82")},
		{OsVersion: proto.String("14.7"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18G69")},
		{OsVersion: proto.String("14.6"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18F72")},
		{OsVersion: proto.String("14.5.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18E212")},
		{OsVersion: proto.String("14.5"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18E199")},
		{OsVersion: proto.String("14.4.2"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18D70")},
		{OsVersion: proto.String("14.4.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18D61")},
		{OsVersion: proto.String("14.4"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18D52")},
		{OsVersion: proto.String("14.3"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18C66")},
		{OsVersion: proto.String("14.2.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18B121")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18B111")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18B92")},
		{OsVersion: proto.String("14.1"), Device: proto.String("iphone 12"), OsBuildNumber: proto.String("18A8395")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19C56")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("14.8"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18H17")},
		{OsVersion: proto.String("14.7.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18G82")},
		{OsVersion: proto.String("14.7"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18G69")},
		{OsVersion: proto.String("14.5.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18E212")},
		{OsVersion: proto.String("14.5"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18E199")},
		{OsVersion: proto.String("14.4.2"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18D70")},
		{OsVersion: proto.String("14.4.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18D61")},
		{OsVersion: proto.String("14.4"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18D52")},
		{OsVersion: proto.String("14.3"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18C66")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18B92")},
		{OsVersion: proto.String("14.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18A8395")},
		{OsVersion: proto.String("14.0.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18A393")},
		{OsVersion: proto.String("14.0"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("18A373")},
		{OsVersion: proto.String("13.7"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("17H35")},
		{OsVersion: proto.String("13.6.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("17G80")},
		{OsVersion: proto.String("13.6"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("17G68")},
		{OsVersion: proto.String("13.5.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("17F80")},
		{OsVersion: proto.String("13.5"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("17F75")},
		{OsVersion: proto.String("13.4.1"), Device: proto.String("iphnoe SE 2020"), OsBuildNumber: proto.String("17E8258")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19C56")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("14.8"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18H17")},
		{OsVersion: proto.String("14.7.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18G82")},
		{OsVersion: proto.String("14.7"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18G69")},
		{OsVersion: proto.String("14.6"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18F72")},
		{OsVersion: proto.String("14.5.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18E212")},
		{OsVersion: proto.String("14.5"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18E199")},
		{OsVersion: proto.String("14.4.2"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18D70")},
		{OsVersion: proto.String("14.4.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18D61")},
		{OsVersion: proto.String("14.4"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18D52")},
		{OsVersion: proto.String("14.3"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18C66")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18B92")},
		{OsVersion: proto.String("14.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18A8395")},
		{OsVersion: proto.String("14.0.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18A393")},
		{OsVersion: proto.String("14.0"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("18A373")},
		{OsVersion: proto.String("13.7"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17H35")},
		{OsVersion: proto.String("13.6.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17G80")},
		{OsVersion: proto.String("13.6"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17G68")},
		{OsVersion: proto.String("13.5.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17F80")},
		{OsVersion: proto.String("13.5"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17F75")},
		{OsVersion: proto.String("13.4.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17E262")},
		{OsVersion: proto.String("13.4"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17E255")},
		{OsVersion: proto.String("13.3.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17D50")},
		{OsVersion: proto.String("13.3"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17C54")},
		{OsVersion: proto.String("13.2.3"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17B111")},
		{OsVersion: proto.String("13.2.2"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17B102")},
		{OsVersion: proto.String("13.2"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17B84")},
		{OsVersion: proto.String("13.1.3"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17A878")},
		{OsVersion: proto.String("13.1.2"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17A860")},
		{OsVersion: proto.String("13.1.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17A854")},
		{OsVersion: proto.String("13.1"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17A844")},
		{OsVersion: proto.String("13.0"), Device: proto.String("iphone 11 pro"), OsBuildNumber: proto.String("17A577")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19C56")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("14.8"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18H17")},
		{OsVersion: proto.String("14.7.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18G82")},
		{OsVersion: proto.String("14.7"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18G69")},
		{OsVersion: proto.String("14.6"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18F72")},
		{OsVersion: proto.String("14.5.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18E212")},
		{OsVersion: proto.String("14.5"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18E199")},
		{OsVersion: proto.String("14.4.2"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18D70")},
		{OsVersion: proto.String("14.4.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18D61")},
		{OsVersion: proto.String("14.4"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18D52")},
		{OsVersion: proto.String("14.3"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18C66")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18B92")},
		{OsVersion: proto.String("14.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18A8395")},
		{OsVersion: proto.String("14.0.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18A393")},
		{OsVersion: proto.String("14.0"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("18A373")},
		{OsVersion: proto.String("13.7"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17H35")},
		{OsVersion: proto.String("13.6.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17G80")},
		{OsVersion: proto.String("13.6"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17G68")},
		{OsVersion: proto.String("13.5.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17F80")},
		{OsVersion: proto.String("13.5"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17F75")},
		{OsVersion: proto.String("13.4.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17E262")},
		{OsVersion: proto.String("13.4"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17E255")},
		{OsVersion: proto.String("13.3.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17D50")},
		{OsVersion: proto.String("13.3"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17C54")},
		{OsVersion: proto.String("13.2.3"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17B111")},
		{OsVersion: proto.String("13.2.2"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17B102")},
		{OsVersion: proto.String("13.2"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17B84")},
		{OsVersion: proto.String("13.1.3"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17A878")},
		{OsVersion: proto.String("13.1.2"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17A860")},
		{OsVersion: proto.String("13.1.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17A854")},
		{OsVersion: proto.String("13.1"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17A844")},
		{OsVersion: proto.String("13.0"), Device: proto.String("iphone 11 "), OsBuildNumber: proto.String("17A577")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19C56")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("14.8"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18H17")},
		{OsVersion: proto.String("14.7.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18G82")},
		{OsVersion: proto.String("14.7"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18G69")},
		{OsVersion: proto.String("14.6"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18F72")},
		{OsVersion: proto.String("14.5.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18E212")},
		{OsVersion: proto.String("14.5"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18E199")},
		{OsVersion: proto.String("14.4.2"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18D70")},
		{OsVersion: proto.String("14.4.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18D61")},
		{OsVersion: proto.String("14.4"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18D52")},
		{OsVersion: proto.String("14.3"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18C66")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18B92")},
		{OsVersion: proto.String("14.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18A8395")},
		{OsVersion: proto.String("14.0.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18A393")},
		{OsVersion: proto.String("14.0"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("18A373")},
		{OsVersion: proto.String("13.7"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17H35")},
		{OsVersion: proto.String("13.6.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17G80")},
		{OsVersion: proto.String("13.6"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17G68")},
		{OsVersion: proto.String("13.5.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17F80")},
		{OsVersion: proto.String("13.5"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17F75")},
		{OsVersion: proto.String("13.4.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17E262")},
		{OsVersion: proto.String("13.4"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17E255")},
		{OsVersion: proto.String("13.3.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17D50")},
		{OsVersion: proto.String("13.3"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17C54")},
		{OsVersion: proto.String("13.2.3"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17B111")},
		{OsVersion: proto.String("13.2.2"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17B102")},
		{OsVersion: proto.String("13.2"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17B84")},
		{OsVersion: proto.String("13.1.3"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17A878")},
		{OsVersion: proto.String("13.1.2"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17A860")},
		{OsVersion: proto.String("13.1.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17A854")},
		{OsVersion: proto.String("13.1"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17A844")},
		{OsVersion: proto.String("13.0"), Device: proto.String("iPhone 11 Pro Max"), OsBuildNumber: proto.String("17A577")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19C56")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("14.8"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18H17")},
		{OsVersion: proto.String("14.7.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18G82")},
		{OsVersion: proto.String("14.7"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18G69")},
		{OsVersion: proto.String("14.6"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18F72")},
		{OsVersion: proto.String("14.5.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18E212")},
		{OsVersion: proto.String("14.5"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18E199")},
		{OsVersion: proto.String("14.4.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18D70")},
		{OsVersion: proto.String("14.4.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18D61")},
		{OsVersion: proto.String("14.4"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18D52")},
		{OsVersion: proto.String("14.3"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18C66")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18B92")},
		{OsVersion: proto.String("14.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18A8395")},
		{OsVersion: proto.String("14.0.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18A393")},
		{OsVersion: proto.String("14.0"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("18A373")},
		{OsVersion: proto.String("13.7"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17H35")},
		{OsVersion: proto.String("13.6.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17G80")},
		{OsVersion: proto.String("13.6"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17G68")},
		{OsVersion: proto.String("13.5.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17F80")},
		{OsVersion: proto.String("13.5"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17F75")},
		{OsVersion: proto.String("13.4.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17E262")},
		{OsVersion: proto.String("13.4"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17E255")},
		{OsVersion: proto.String("13.3.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17D50")},
		{OsVersion: proto.String("13.3"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17C54")},
		{OsVersion: proto.String("13.2.3"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17B111")},
		{OsVersion: proto.String("13.2.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17B102")},
		{OsVersion: proto.String("13.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17B84")},
		{OsVersion: proto.String("13.1.3"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17A878")},
		{OsVersion: proto.String("13.1.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17A860")},
		{OsVersion: proto.String("13.1.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17A854")},
		{OsVersion: proto.String("13.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17A844")},
		{OsVersion: proto.String("13.0"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("17A577")},
		{OsVersion: proto.String("12.4.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16G102")},
		{OsVersion: proto.String("12.4"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16G77")},
		{OsVersion: proto.String("12.3.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16F203")},
		{OsVersion: proto.String("12.3"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16F156")},
		{OsVersion: proto.String("12.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16E227")},
		{OsVersion: proto.String("12.1.4"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16D57")},
		{OsVersion: proto.String("12.1.3"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16D40")},
		{OsVersion: proto.String("12.1.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16C104")},
		{OsVersion: proto.String("12.1.2"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16C101")},
		{OsVersion: proto.String("12.1.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16C50")},
		{OsVersion: proto.String("12.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16B94")},
		{OsVersion: proto.String("12.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16B93")},
		{OsVersion: proto.String("12.0.1"), Device: proto.String("iphone XR"), OsBuildNumber: proto.String("16A405")},
		{OsVersion: proto.String("16.6"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20G75")},
		{OsVersion: proto.String("16.4"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20E247")},
		{OsVersion: proto.String("16.5.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20F75")},
		{OsVersion: proto.String("16.5"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20F66")},
		{OsVersion: proto.String("16.4.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20E252")},
		{OsVersion: proto.String("16.3.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20D67")},
		{OsVersion: proto.String("16.3"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20D47")},
		{OsVersion: proto.String("16.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20C65")},
		{OsVersion: proto.String("16.1.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20B110")},
		{OsVersion: proto.String("16.1.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20B101")},
		{OsVersion: proto.String("16.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20B82")},
		{OsVersion: proto.String("16.0.3"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20A392")},
		{OsVersion: proto.String("16.0.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20A380")},
		{OsVersion: proto.String("16.0"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("20A362")},
		{OsVersion: proto.String("15.6.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19G82")},
		{OsVersion: proto.String("15.6"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19G71")},
		{OsVersion: proto.String("15.5"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19F77")},
		{OsVersion: proto.String("15.4.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19E258")},
		{OsVersion: proto.String("15.4"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19E241")},
		{OsVersion: proto.String("15.3.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19D52")},
		{OsVersion: proto.String("15.3"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19D50")},
		{OsVersion: proto.String("15.2.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19C63")},
		{OsVersion: proto.String("15.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19C56")},
		{OsVersion: proto.String("15.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19B74")},
		{OsVersion: proto.String("15.0.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19A404")},
		{OsVersion: proto.String("15.0.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19A348")},
		{OsVersion: proto.String("15.0"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("19A346")},
		{OsVersion: proto.String("14.8"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18H17")},
		{OsVersion: proto.String("14.7.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18G82")},
		{OsVersion: proto.String("14.7"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18G69")},
		{OsVersion: proto.String("14.6"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18F72")},
		{OsVersion: proto.String("14.5.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18E212")},
		{OsVersion: proto.String("14.5"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18E199")},
		{OsVersion: proto.String("14.4.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18D70")},
		{OsVersion: proto.String("14.4.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18D61")},
		{OsVersion: proto.String("14.4"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18D52")},
		{OsVersion: proto.String("14.3"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18C66")},
		{OsVersion: proto.String("14.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18B92")},
		{OsVersion: proto.String("14.0.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18A393")},
		{OsVersion: proto.String("14.0"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("18A373")},
		{OsVersion: proto.String("13.7"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17H35")},
		{OsVersion: proto.String("13.6.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17G80")},
		{OsVersion: proto.String("13.6"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17G68")},
		{OsVersion: proto.String("13.5.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17F80")},
		{OsVersion: proto.String("13.5"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17F75")},
		{OsVersion: proto.String("13.4.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17E262")},
		{OsVersion: proto.String("13.4"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17E255")},
		{OsVersion: proto.String("13.3.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17D50")},
		{OsVersion: proto.String("13.3"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17C54")},
		{OsVersion: proto.String("13.2.3"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17B111")},
		{OsVersion: proto.String("13.2.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17B102")},
		{OsVersion: proto.String("13.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17B84")},
		{OsVersion: proto.String("13.1.3"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17A878")},
		{OsVersion: proto.String("13.1.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17A861")},
		{OsVersion: proto.String("13.1.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17A854")},
		{OsVersion: proto.String("13.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17A844")},
		{OsVersion: proto.String("13.0"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("17A577")},
		{OsVersion: proto.String("12.4.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16G102")},
		{OsVersion: proto.String("12.4"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16G77")},
		{OsVersion: proto.String("12.3.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16F203")},
		{OsVersion: proto.String("12.3"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16F156")},
		{OsVersion: proto.String("12.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16E227")},
		{OsVersion: proto.String("12.1.4"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16D57")},
		{OsVersion: proto.String("12.1.3"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16D40")},
		{OsVersion: proto.String("12.1.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16C104")},
		{OsVersion: proto.String("12.1.2"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16C101")},
		{OsVersion: proto.String("12.1.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16C50")},
		{OsVersion: proto.String("12.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16B92")},
		{OsVersion: proto.String("12.0.1"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16A405")},
		{OsVersion: proto.String("12.0"), Device: proto.String("iPhone XS Max 中国"), OsBuildNumber: proto.String("16A366")},
	}

	// 设置随机数种子
	rand.Seed(time.Now().UnixNano())
	// 生成一个随机索引
	randomIndex := rand.Intn(len(globaleUserDeviceConfigs))

	// 随机选择的元素
	randomElement := globaleUserDeviceConfigs[randomIndex]
	randomElement.PhoneId = proto.String(strings.ToUpper(uuid.New().String()))
	return randomElement
}
