// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: protobuf/account_detail.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserJid          uint64 `protobuf:"varint,1,opt,name=userJid,proto3" json:"userJid,omitempty"`
	PrivateKey       []byte `protobuf:"bytes,2,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	PublicKey        []byte `protobuf:"bytes,3,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	PublicMsgKey     []byte `protobuf:"bytes,4,opt,name=publicMsgKey,proto3" json:"publicMsgKey,omitempty"`
	PrivateMsgKey    []byte `protobuf:"bytes,5,opt,name=privateMsgKey,proto3" json:"privateMsgKey,omitempty"`
	Identify         []byte `protobuf:"bytes,6,opt,name=identify,proto3" json:"identify,omitempty"`
	ResumptionSecret []byte `protobuf:"bytes,7,opt,name=resumptionSecret,proto3" json:"resumptionSecret,omitempty"`
	ClientPayload    []byte `protobuf:"bytes,8,opt,name=clientPayload,proto3" json:"clientPayload,omitempty"`
}

func (x *AccountDetail) Reset() {
	*x = AccountDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_account_detail_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountDetail) ProtoMessage() {}

func (x *AccountDetail) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_account_detail_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountDetail.ProtoReflect.Descriptor instead.
func (*AccountDetail) Descriptor() ([]byte, []int) {
	return file_protobuf_account_detail_proto_rawDescGZIP(), []int{0}
}

func (x *AccountDetail) GetUserJid() uint64 {
	if x != nil {
		return x.UserJid
	}
	return 0
}

func (x *AccountDetail) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *AccountDetail) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *AccountDetail) GetPublicMsgKey() []byte {
	if x != nil {
		return x.PublicMsgKey
	}
	return nil
}

func (x *AccountDetail) GetPrivateMsgKey() []byte {
	if x != nil {
		return x.PrivateMsgKey
	}
	return nil
}

func (x *AccountDetail) GetIdentify() []byte {
	if x != nil {
		return x.Identify
	}
	return nil
}

func (x *AccountDetail) GetResumptionSecret() []byte {
	if x != nil {
		return x.ResumptionSecret
	}
	return nil
}

func (x *AccountDetail) GetClientPayload() []byte {
	if x != nil {
		return x.ClientPayload
	}
	return nil
}

type TgAccountDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber string `protobuf:"bytes,1,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	AppId       uint64 `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	AppHash     string `protobuf:"bytes,3,opt,name=appHash,proto3" json:"appHash,omitempty"`
}

func (x *TgAccountDetail) Reset() {
	*x = TgAccountDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_account_detail_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgAccountDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgAccountDetail) ProtoMessage() {}

func (x *TgAccountDetail) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_account_detail_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgAccountDetail.ProtoReflect.Descriptor instead.
func (*TgAccountDetail) Descriptor() ([]byte, []int) {
	return file_protobuf_account_detail_proto_rawDescGZIP(), []int{1}
}

func (x *TgAccountDetail) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *TgAccountDetail) GetAppId() uint64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *TgAccountDetail) GetAppHash() string {
	if x != nil {
		return x.AppHash
	}
	return ""
}

type AccountLogin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsLogin    bool   `protobuf:"varint,1,opt,name=isLogin,proto3" json:"isLogin,omitempty"`
	GrpcServer string `protobuf:"bytes,2,opt,name=grpcServer,proto3" json:"grpcServer,omitempty"`
	UserJid    uint64 `protobuf:"varint,3,opt,name=userJid,proto3" json:"userJid,omitempty"`
	LastName   string `protobuf:"bytes,4,opt,name=LastName,proto3" json:"LastName,omitempty"`
	FirstName  string `protobuf:"bytes,5,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	UserID     int64  `protobuf:"varint,6,opt,name=UserID,proto3" json:"UserID,omitempty"`
	UserName   string `protobuf:"bytes,7,opt,name=UserName,proto3" json:"UserName,omitempty"`
}

func (x *AccountLogin) Reset() {
	*x = AccountLogin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_account_detail_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountLogin) ProtoMessage() {}

func (x *AccountLogin) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_account_detail_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountLogin.ProtoReflect.Descriptor instead.
func (*AccountLogin) Descriptor() ([]byte, []int) {
	return file_protobuf_account_detail_proto_rawDescGZIP(), []int{2}
}

func (x *AccountLogin) GetIsLogin() bool {
	if x != nil {
		return x.IsLogin
	}
	return false
}

func (x *AccountLogin) GetGrpcServer() string {
	if x != nil {
		return x.GrpcServer
	}
	return ""
}

func (x *AccountLogin) GetUserJid() uint64 {
	if x != nil {
		return x.UserJid
	}
	return 0
}

func (x *AccountLogin) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AccountLogin) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AccountLogin) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *AccountLogin) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type ServiceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IP          string `protobuf:"bytes,1,opt,name=IP,proto3" json:"IP,omitempty"`
	Connections uint32 `protobuf:"varint,2,opt,name=Connections,proto3" json:"Connections,omitempty"`
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_account_detail_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_account_detail_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_protobuf_account_detail_proto_rawDescGZIP(), []int{3}
}

func (x *ServiceInfo) GetIP() string {
	if x != nil {
		return x.IP
	}
	return ""
}

func (x *ServiceInfo) GetConnections() uint32 {
	if x != nil {
		return x.Connections
	}
	return 0
}

type MyUserTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Age   string `protobuf:"bytes,2,opt,name=Age,proto3" json:"Age,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *MyUserTest) Reset() {
	*x = MyUserTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_account_detail_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MyUserTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MyUserTest) ProtoMessage() {}

func (x *MyUserTest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_account_detail_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MyUserTest.ProtoReflect.Descriptor instead.
func (*MyUserTest) Descriptor() ([]byte, []int) {
	return file_protobuf_account_detail_proto_rawDescGZIP(), []int{4}
}

func (x *MyUserTest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MyUserTest) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

func (x *MyUserTest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type TgAccountSessionTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JsonByte []byte `protobuf:"bytes,1,opt,name=jsonByte,proto3" json:"jsonByte,omitempty"`
}

func (x *TgAccountSessionTest) Reset() {
	*x = TgAccountSessionTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_account_detail_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgAccountSessionTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgAccountSessionTest) ProtoMessage() {}

func (x *TgAccountSessionTest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_account_detail_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgAccountSessionTest.ProtoReflect.Descriptor instead.
func (*TgAccountSessionTest) Descriptor() ([]byte, []int) {
	return file_protobuf_account_detail_proto_rawDescGZIP(), []int{5}
}

func (x *TgAccountSessionTest) GetJsonByte() []byte {
	if x != nil {
		return x.JsonByte
	}
	return nil
}

type TgAccountSession struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version int32 `protobuf:"varint,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Data    *Data `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"` //    bytes session = 1;
}

func (x *TgAccountSession) Reset() {
	*x = TgAccountSession{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_account_detail_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TgAccountSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TgAccountSession) ProtoMessage() {}

func (x *TgAccountSession) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_account_detail_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TgAccountSession.ProtoReflect.Descriptor instead.
func (*TgAccountSession) Descriptor() ([]byte, []int) {
	return file_protobuf_account_detail_proto_rawDescGZIP(), []int{6}
}

func (x *TgAccountSession) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TgAccountSession) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config    *Config `protobuf:"bytes,1,opt,name=Config,proto3" json:"Config,omitempty"`
	DC        int32   `protobuf:"varint,2,opt,name=DC,proto3" json:"DC,omitempty"`
	Addr      string  `protobuf:"bytes,3,opt,name=Addr,proto3" json:"Addr,omitempty"`
	AuthKey   string  `protobuf:"bytes,4,opt,name=AuthKey,proto3" json:"AuthKey,omitempty"`
	AuthKeyID string  `protobuf:"bytes,5,opt,name=AuthKeyID,proto3" json:"AuthKeyID,omitempty"`
	Salt      int64   `protobuf:"varint,6,opt,name=Salt,proto3" json:"Salt,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_account_detail_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_account_detail_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_protobuf_account_detail_proto_rawDescGZIP(), []int{7}
}

func (x *Data) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Data) GetDC() int32 {
	if x != nil {
		return x.DC
	}
	return 0
}

func (x *Data) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Data) GetAuthKey() string {
	if x != nil {
		return x.AuthKey
	}
	return ""
}

func (x *Data) GetAuthKeyID() string {
	if x != nil {
		return x.AuthKeyID
	}
	return ""
}

func (x *Data) GetSalt() int64 {
	if x != nil {
		return x.Salt
	}
	return 0
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockedMode     bool        `protobuf:"varint,1,opt,name=BlockedMode,proto3" json:"BlockedMode,omitempty"`
	ForceTryIpv6    bool        `protobuf:"varint,2,opt,name=ForceTryIpv6,proto3" json:"ForceTryIpv6,omitempty"`
	Date            int32       `protobuf:"varint,3,opt,name=Date,proto3" json:"Date,omitempty"`
	Expires         int32       `protobuf:"varint,4,opt,name=Expires,proto3" json:"Expires,omitempty"`
	TestMode        bool        `protobuf:"varint,5,opt,name=TestMode,proto3" json:"TestMode,omitempty"`
	ThisDC          int32       `protobuf:"varint,6,opt,name=ThisDC,proto3" json:"ThisDC,omitempty"`
	DCOptions       []*DCOption `protobuf:"bytes,7,rep,name=DCOptions,proto3" json:"DCOptions,omitempty"`
	DCTxtDomainName string      `protobuf:"bytes,8,opt,name=DCTxtDomainName,proto3" json:"DCTxtDomainName,omitempty"`
	TmpSessions     int32       `protobuf:"varint,9,opt,name=TmpSessions,proto3" json:"TmpSessions,omitempty"`
	WebfileDCID     int32       `protobuf:"varint,10,opt,name=WebfileDCID,proto3" json:"WebfileDCID,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_account_detail_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_account_detail_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_protobuf_account_detail_proto_rawDescGZIP(), []int{8}
}

func (x *Config) GetBlockedMode() bool {
	if x != nil {
		return x.BlockedMode
	}
	return false
}

func (x *Config) GetForceTryIpv6() bool {
	if x != nil {
		return x.ForceTryIpv6
	}
	return false
}

func (x *Config) GetDate() int32 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Config) GetExpires() int32 {
	if x != nil {
		return x.Expires
	}
	return 0
}

func (x *Config) GetTestMode() bool {
	if x != nil {
		return x.TestMode
	}
	return false
}

func (x *Config) GetThisDC() int32 {
	if x != nil {
		return x.ThisDC
	}
	return 0
}

func (x *Config) GetDCOptions() []*DCOption {
	if x != nil {
		return x.DCOptions
	}
	return nil
}

func (x *Config) GetDCTxtDomainName() string {
	if x != nil {
		return x.DCTxtDomainName
	}
	return ""
}

func (x *Config) GetTmpSessions() int32 {
	if x != nil {
		return x.TmpSessions
	}
	return 0
}

func (x *Config) GetWebfileDCID() int32 {
	if x != nil {
		return x.WebfileDCID
	}
	return 0
}

type DCOption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Flags             uint32 `protobuf:"varint,1,opt,name=Flags,proto3" json:"Flags,omitempty"`
	Ipv6              bool   `protobuf:"varint,2,opt,name=Ipv6,proto3" json:"Ipv6,omitempty"`
	MediaOnly         bool   `protobuf:"varint,3,opt,name=MediaOnly,proto3" json:"MediaOnly,omitempty"`
	TCPObfuscatedOnly bool   `protobuf:"varint,4,opt,name=TCPObfuscatedOnly,proto3" json:"TCPObfuscatedOnly,omitempty"`
	CDN               bool   `protobuf:"varint,5,opt,name=CDN,proto3" json:"CDN,omitempty"`
	Static            bool   `protobuf:"varint,6,opt,name=Static,proto3" json:"Static,omitempty"`
	ThisPortOnly      bool   `protobuf:"varint,7,opt,name=ThisPortOnly,proto3" json:"ThisPortOnly,omitempty"`
	ID                int32  `protobuf:"varint,8,opt,name=ID,proto3" json:"ID,omitempty"`
	IPAddress         string `protobuf:"bytes,9,opt,name=IPAddress,proto3" json:"IPAddress,omitempty"`
	Port              int32  `protobuf:"varint,10,opt,name=Port,proto3" json:"Port,omitempty"`
	Secret            []byte `protobuf:"bytes,11,opt,name=Secret,proto3" json:"Secret,omitempty"`
}

func (x *DCOption) Reset() {
	*x = DCOption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_account_detail_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DCOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DCOption) ProtoMessage() {}

func (x *DCOption) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_account_detail_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DCOption.ProtoReflect.Descriptor instead.
func (*DCOption) Descriptor() ([]byte, []int) {
	return file_protobuf_account_detail_proto_rawDescGZIP(), []int{9}
}

func (x *DCOption) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *DCOption) GetIpv6() bool {
	if x != nil {
		return x.Ipv6
	}
	return false
}

func (x *DCOption) GetMediaOnly() bool {
	if x != nil {
		return x.MediaOnly
	}
	return false
}

func (x *DCOption) GetTCPObfuscatedOnly() bool {
	if x != nil {
		return x.TCPObfuscatedOnly
	}
	return false
}

func (x *DCOption) GetCDN() bool {
	if x != nil {
		return x.CDN
	}
	return false
}

func (x *DCOption) GetStatic() bool {
	if x != nil {
		return x.Static
	}
	return false
}

func (x *DCOption) GetThisPortOnly() bool {
	if x != nil {
		return x.ThisPortOnly
	}
	return false
}

func (x *DCOption) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *DCOption) GetIPAddress() string {
	if x != nil {
		return x.IPAddress
	}
	return ""
}

func (x *DCOption) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DCOption) GetSecret() []byte {
	if x != nil {
		return x.Secret
	}
	return nil
}

var File_protobuf_account_detail_proto protoreflect.FileDescriptor

var file_protobuf_account_detail_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9f, 0x02, 0x0a, 0x0d, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4a, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4a, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a,
	0x0d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67, 0x4b, 0x65, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x70, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67,
	0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x12,
	0x2a, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63,
	0x72, 0x65, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x72, 0x65, 0x73, 0x75, 0x6d,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74, 0x12, 0x24, 0x0a, 0x0d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x22, 0x63, 0x0a, 0x0f, 0x54, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x70, 0x70, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x70, 0x70, 0x48, 0x61, 0x73, 0x68, 0x22, 0xd0, 0x01, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x73, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x73, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x72, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4a, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72, 0x4a, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4c,
	0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c,
	0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x46, 0x69, 0x72, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x55, 0x73, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3f, 0x0a, 0x0b, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x50, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x50, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x48, 0x0a, 0x0a, 0x4d, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x54, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x41, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x41, 0x67, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x22, 0x32, 0x0a, 0x14, 0x54, 0x67, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x6a, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08,
	0x6a, 0x73, 0x6f, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x22, 0x47, 0x0a, 0x10, 0x54, 0x67, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x22, 0x97, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x1f, 0x0a, 0x06, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x52, 0x06, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x44,
	0x43, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x44, 0x43, 0x12, 0x12, 0x0a, 0x04, 0x41,
	0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x41, 0x64, 0x64, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x41, 0x75, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x41, 0x75, 0x74, 0x68, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x75, 0x74,
	0x68, 0x4b, 0x65, 0x79, 0x49, 0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x75,
	0x74, 0x68, 0x4b, 0x65, 0x79, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x61, 0x6c, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x53, 0x61, 0x6c, 0x74, 0x22, 0xc7, 0x02, 0x0a, 0x06,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x65,
	0x64, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x42, 0x6c, 0x6f,
	0x63, 0x6b, 0x65, 0x64, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x6f, 0x72, 0x63,
	0x65, 0x54, 0x72, 0x79, 0x49, 0x70, 0x76, 0x36, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x46, 0x6f, 0x72, 0x63, 0x65, 0x54, 0x72, 0x79, 0x49, 0x70, 0x76, 0x36, 0x12, 0x12, 0x0a, 0x04,
	0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x54, 0x65,
	0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x54, 0x65,
	0x73, 0x74, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x68, 0x69, 0x73, 0x44, 0x43,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x54, 0x68, 0x69, 0x73, 0x44, 0x43, 0x12, 0x27,
	0x0a, 0x09, 0x44, 0x43, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x44, 0x43, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x44, 0x43,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x0a, 0x0f, 0x44, 0x43, 0x54, 0x78, 0x74,
	0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x44, 0x43, 0x54, 0x78, 0x74, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x6d, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x54, 0x6d, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x57, 0x65, 0x62, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x43,
	0x49, 0x44, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x57, 0x65, 0x62, 0x66, 0x69, 0x6c,
	0x65, 0x44, 0x43, 0x49, 0x44, 0x22, 0xa8, 0x02, 0x0a, 0x08, 0x44, 0x43, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x46, 0x6c, 0x61, 0x67, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x70, 0x76, 0x36,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x49, 0x70, 0x76, 0x36, 0x12, 0x1c, 0x0a, 0x09,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x11, 0x54, 0x43,
	0x50, 0x4f, 0x62, 0x66, 0x75, 0x73, 0x63, 0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x54, 0x43, 0x50, 0x4f, 0x62, 0x66, 0x75, 0x73, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x43, 0x44, 0x4e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x43, 0x44, 0x4e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x63, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x63, 0x12, 0x22, 0x0a, 0x0c, 0x54, 0x68, 0x69, 0x73, 0x50, 0x6f, 0x72, 0x74, 0x4f, 0x6e,
	0x6c, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x54, 0x68, 0x69, 0x73, 0x50, 0x6f,
	0x72, 0x74, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x49, 0x50, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x72,
	0x65, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x53, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_account_detail_proto_rawDescOnce sync.Once
	file_protobuf_account_detail_proto_rawDescData = file_protobuf_account_detail_proto_rawDesc
)

func file_protobuf_account_detail_proto_rawDescGZIP() []byte {
	file_protobuf_account_detail_proto_rawDescOnce.Do(func() {
		file_protobuf_account_detail_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_account_detail_proto_rawDescData)
	})
	return file_protobuf_account_detail_proto_rawDescData
}

var file_protobuf_account_detail_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protobuf_account_detail_proto_goTypes = []interface{}{
	(*AccountDetail)(nil),        // 0: AccountDetail
	(*TgAccountDetail)(nil),      // 1: TgAccountDetail
	(*AccountLogin)(nil),         // 2: AccountLogin
	(*ServiceInfo)(nil),          // 3: ServiceInfo
	(*MyUserTest)(nil),           // 4: MyUserTest
	(*TgAccountSessionTest)(nil), // 5: TgAccountSessionTest
	(*TgAccountSession)(nil),     // 6: TgAccountSession
	(*Data)(nil),                 // 7: Data
	(*Config)(nil),               // 8: Config
	(*DCOption)(nil),             // 9: DCOption
}
var file_protobuf_account_detail_proto_depIdxs = []int32{
	7, // 0: TgAccountSession.Data:type_name -> Data
	8, // 1: Data.Config:type_name -> Config
	9, // 2: Config.DCOptions:type_name -> DCOption
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_protobuf_account_detail_proto_init() }
func file_protobuf_account_detail_proto_init() {
	if File_protobuf_account_detail_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_account_detail_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_account_detail_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgAccountDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_account_detail_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountLogin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_account_detail_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_account_detail_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MyUserTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_account_detail_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgAccountSessionTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_account_detail_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TgAccountSession); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_account_detail_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_account_detail_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_account_detail_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DCOption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_account_detail_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_account_detail_proto_goTypes,
		DependencyIndexes: file_protobuf_account_detail_proto_depIdxs,
		MessageInfos:      file_protobuf_account_detail_proto_msgTypes,
	}.Build()
	File_protobuf_account_detail_proto = out.File
	file_protobuf_account_detail_proto_rawDesc = nil
	file_protobuf_account_detail_proto_goTypes = nil
	file_protobuf_account_detail_proto_depIdxs = nil
}
