apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app/name: arthas
  name: arthas
spec:
  replicas: 1
  selector:
    matchLabels:
      app/name: arthas
  template:
    metadata:
      labels:
        app/name: arthas
      namespace: arts-system
    spec:
      containers:
        - name: arthas
          command:
            - arthas
            - telegram
            - --web.listen-address=0.0.0.0:31502
            - --web.name-space=prod
            - --web.env=prod
            - --web.version=latest
            - --callback.server.address=kafka-headless:9092
            - --etcd.endpoint=8.219.159.49:43279
            - --etcd.username=root
            - --etcd.password=HpIF14zNxvNBvGsg_Au
